module.exports = [
    "arsenal",
    "aston villa",
    "bournemouth",
    "chelsea",
    "crystal palace",
    "everton",
    "leicester",
    "leicester city",
    "liverpool",
    "man city",
    "man united",
    "man utd",
    "manchester city",
    "manchester united",
    "manchester utd",
    "newcastle",
    "norwich",
    "norwich city",
    "southampton",
    "spurs",
    "stoke",
    "stoke city",
    "sunderland",
    "swansea",
    "swansea city",
    "tottenham",
    "tottenham hotspur",
    "villa",
    "watford",
    "west brom",
    "west bromwich albion",
    "west ham",
    "west ham united"
];
