module.exports = {
    'shortname': {
        'Arsenal': 'arsenal',
        'Aston Villa': 'avfc',
        'Bournemouth': 'afcb',
        'Chelsea': 'chelsea',
        'Crystal Palace': 'cpfc',
        'Everton': 'everton',
        'Leicester': 'lcfc',
        'Liverpool': 'lfc',
        'Man City': 'mcfc',
        'Man Utd': 'mufc',
        'Newcastle': 'nufc',
        'Norwich': 'ncfc',
        'Southampton': 'southampton',
        'Stoke': 'stokecity',
        'Sunderland': 'safc',
        'Swansea': 'swansea',
        'Tottenham': 'thfc',
        'Watford': 'watford',
        'West Brom': 'wba',
        'West Ham': 'whufc'
    },
    'fullName': {
        'Arsenal': 'Arsenal',
        'Aston Villa': 'Aston Villa',
        'Bournemouth': 'Bournemouth',
        'Chelsea': 'Chelsea',
        'Crystal Palace': 'Crystal Palace',
        'Everton': 'Everton',
        'Leicester': 'Leicester',
        'Liverpool': 'Liverpool',
        'Man City': 'Manchester City',
        'Man Utd': 'Manchester United',
        'Newcastle': 'Newcastle',
        'Norwich': 'Norwich',
        'Southampton': 'Southampton',
        'Stoke': 'Stoke City',
        'Sunderland': 'Sunderland',
        'Swansea': 'Swansea City',
        'Tottenham': 'Tottenham Hotspur',
        'Watford': 'Watford',
        'West Brom': 'West Bromwich Albion',
        'West Ham': 'West Ham United'
    }
}
